global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:5000']

  - job_name: 'restaurant-service'
    static_configs:
      - targets: ['restaurant-service:5000']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:5000']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:5000']
